"use client";

import { useEffect } from "react";

export default function TermsPage() {
  useEffect(() => {
    window.scrollTo(0, 0);
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("visible");
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1, rootMargin: "0px 0px -40px 0px" }
    );

    document.querySelectorAll(".fade-in").forEach((el) => observer.observe(el));

    return () => {
      observer.disconnect();
    };
  }, []);

  return (
    <main>
      <div className="legal-header fade-in">
        <div className="container">
          <h1 className="legal-title">Terms of Service</h1>
          <p className="legal-effective">Effective date: 1 April 2026</p>
        </div>
      </div>
      <section className="legal-page">
        <div className="container">
          <div className="legal-body fade-in fade-in-delay-1">

            <h2>1. Introduction</h2>
            <p>These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the Caio website and platform (&ldquo;Service&rdquo;). By accessing or using the Service, you agree to be bound by these Terms. If you do not agree, you may not use the Service.</p>
            <p>Caio provides compliance infrastructure for recruitment agencies operating in regulated sectors including education, healthcare, and social care. The Service includes automated compliance checking, document management, candidate processing, and audit trail generation.</p>

            <h2>2. Definitions</h2>
            <ul>
              <li><strong>&ldquo;Client&rdquo;</strong> means the recruitment agency or organisation that has entered into a subscription agreement with Caio to use the platform</li>
              <li><strong>&ldquo;User&rdquo;</strong> means any individual authorised by a Client to access and use the platform</li>
              <li><strong>&ldquo;Candidate&rdquo;</strong> means any individual whose personal data is processed through the platform as part of the compliance checking process</li>
              <li><strong>&ldquo;Platform&rdquo;</strong> means the Caio web application and associated services</li>
            </ul>

            <h2>3. Use of the Service</h2>
            <h3>3.1 Eligibility</h3>
            <p>The Service is intended for use by recruitment agencies and staffing organisations operating in the United Kingdom. By using the Service, you represent that you have the authority to enter into these Terms on behalf of your organisation.</p>

            <h3>3.2 Acceptable use</h3>
            <p>You agree to use the Service only for its intended purpose: managing candidate compliance in accordance with applicable regulations. You must not:</p>
            <ul>
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorised access to any part of the Service</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
              <li>Reverse engineer, decompile, or disassemble any aspect of the Service</li>
              <li>Use the Service to process data for purposes other than compliance management</li>
              <li>Share account credentials with unauthorised individuals</li>
            </ul>

            <h3>3.3 Account responsibility</h3>
            <p>You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorised use.</p>

            <h2>4. Compliance decisions</h2>
            <p>The platform provides compliance outcomes based on deterministic rules applied to the data and documents provided. It is important to understand the following:</p>
            <ul>
              <li>Caio executes compliance checks against defined regulatory frameworks. The accuracy of outcomes depends on the accuracy and completeness of the data provided</li>
              <li>Compliance outcomes generated by the platform are designed to assist your compliance processes. The Client retains ultimate responsibility for ensuring candidates meet all applicable requirements before placement</li>
              <li>AI agents within the platform perform execution tasks (document collection, data extraction, database queries). Compliance determinations are made by deterministic rules, not by AI models</li>
              <li>While we maintain our rule sets against current regulatory guidance, we do not guarantee that the platform reflects the very latest regulatory changes at all times. Clients should maintain awareness of regulatory developments in their sector</li>
            </ul>

            <h2>5. Data and privacy</h2>
            <p>Our collection and use of personal data is governed by our <a href="/privacy">Privacy Policy</a>. By using the Service, you acknowledge that you have read and understood our Privacy Policy.</p>
            <p>When processing candidate data on behalf of Clients, Caio acts as a data processor. The terms of this processing are set out in a separate Data Processing Agreement entered into between Caio and each Client.</p>
            <p>Clients are responsible for ensuring they have a lawful basis to submit candidate data to the platform, including obtaining any necessary consents.</p>

            <h2>6. Intellectual property</h2>
            <p>All intellectual property rights in the Service, including software, design, content, and trademarks, are owned by Caio or our licensors. These Terms do not grant you any rights to use our intellectual property except as necessary to use the Service.</p>
            <p>Content you submit to the platform (including candidate documents and data) remains your property. You grant Caio a limited licence to process this content solely for the purpose of providing the Service.</p>

            <h2>7. Service availability</h2>
            <p>We aim to maintain high availability of the platform but do not guarantee uninterrupted access. The Service may be temporarily unavailable due to:</p>
            <ul>
              <li>Scheduled maintenance (we will provide reasonable notice where possible)</li>
              <li>Unscheduled maintenance required to address security or performance issues</li>
              <li>Factors beyond our reasonable control, including third-party service outages</li>
            </ul>
            <p>We are not liable for any loss or damage arising from Service unavailability.</p>

            <h2>8. Fees and payment</h2>
            <p>Access to the platform is subject to the subscription fees set out in your Client agreement. Fees are invoiced in accordance with the payment terms specified in that agreement.</p>
            <p>We reserve the right to modify fees upon reasonable notice. Fee changes will not apply to the current billing period.</p>

            <h2>9. Limitation of liability</h2>
            <p>To the maximum extent permitted by law:</p>
            <ul>
              <li>Caio shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunity</li>
              <li>Our total aggregate liability for any claims arising from or related to the Service shall not exceed the total fees paid by you in the 12 months preceding the claim</li>
              <li>We do not exclude or limit liability for death or personal injury caused by negligence, fraud, or any other liability that cannot be excluded by law</li>
            </ul>

            <h2>10. Indemnification</h2>
            <p>You agree to indemnify and hold Caio harmless from any claims, losses, or damages (including reasonable legal fees) arising from:</p>
            <ul>
              <li>Your breach of these Terms</li>
              <li>Your use of the Service in a manner not authorised by these Terms</li>
              <li>Any claim that data you provided through the Service infringes the rights of a third party</li>
            </ul>

            <h2>11. Termination</h2>
            <p>Either party may terminate the Service agreement in accordance with the terms of the Client subscription agreement. Upon termination:</p>
            <ul>
              <li>Your access to the platform will be revoked</li>
              <li>We will retain your data for the period specified in our Privacy Policy and Data Processing Agreement, after which it will be securely deleted</li>
              <li>You may request an export of your data prior to termination</li>
            </ul>
            <p>We may suspend or terminate access immediately if we reasonably believe you are in material breach of these Terms.</p>

            <h2>12. Governing law</h2>
            <p>These Terms are governed by and construed in accordance with the laws of England and Wales. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts of England and Wales.</p>

            <h2>13. Changes to these Terms</h2>
            <p>We may update these Terms from time to time. Material changes will be communicated to Clients via email or through the platform. Continued use of the Service after changes take effect constitutes acceptance of the updated Terms.</p>

            <h2>14. Contact</h2>
            <p>If you have questions about these Terms, contact us at:</p>
            <ul>
              <li>Email: <a href="mailto:legal@usecaio.com">legal@usecaio.com</a></li>
              <li>General enquiries: <a href="mailto:hello@usecaio.com">hello@usecaio.com</a></li>
            </ul>

          </div>
        </div>
      </section>
    </main>
  );
}
